const shortid = require('shortid');

export const homeData = [
  { id: shortid.generate(),
    room: "Kitchen",
    category: "Filters",
    name: "Refrigerator Water Filter",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "6 months",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Kitchen",
    category: "Sponges",
    name: "Sponge",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "2-4 weeks",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Bathroom",
    category: "Toothbrush",
    name: "Toothbrush",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "1-3 months",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Bathroom",
    category: "First Aid Kit",
    name: "First Aid Kit",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Check Expiration"
  },
  { id: shortid.generate(),
    room: "Bathroom",
    category: "Medications",
    name: "Medications",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Check Expiration"
  },
  { id: shortid.generate(),
    room: "Bedroom",
    category: "Smoke Detector",
    name: "Smoke Detector Batteries",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Bedroom",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "30-90 days",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Living Room",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "30-90 days",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Kitchen",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "30-90 days",
    replaceUserPref: "",
    type: "Replace"
  },
  { id: shortid.generate(),
    room: "Kitchen",
    category: "Fire Extinguisher",
    name: "Fire Extinguisher",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Check Expiration"
  },
  { id: shortid.generate(),
    room: "Kitchen",
    category: "Spices",
    name: "Spices",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Check Expiration"
  },
  { id: shortid.generate(),
    room: "Bedroom",
    category: "Carbon Monoxide Detector",
    name: "Carbon Monoxide Detector",
    brand: "",
    model: "",
    lastReplaced: "",
    purchaseLocation: "",
    replaceRecommend: "yearly",
    replaceUserPref: "",
    type: "Check Expiration"
  },
]