const shortid = require('shortid');

export const homeData = [
  { id: 1,
    room: "Kitchen",
    category: "Filters",
    name: "Refrigerator Water Filter",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "6 months",
    userScheduled: "",
    type: "Replace"
  },
  { id: 2,
    room: "Kitchen",
    category: "Sponges",
    name: "Sponge",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "2-4 weeks",
    userScheduled: "",
    type: "Replace"
  },
  { id: 3,
    room: "Bathroom",
    category: "Toothbrush",
    name: "Toothbrush",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "1-3 months",
    userScheduled: "",
    type: "Replace"
  },
  { id: 4,
    room: "Bathroom",
    category: "First Aid Kit",
    name: "First Aid Kit",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Check Expiration"
  },
  { id: 5,
    room: "Bathroom",
    category: "Medications",
    name: "Medications",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Check Expiration"
  },
  { id: 6,
    room: "Bedroom",
    category: "Smoke Detector",
    name: "Smoke Detector Batteries",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Replace"
  },
  { id: 7,
    room: "Bedroom",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "30-90 days",
    userScheduled: "",
    type: "Replace"
  },
  { id: 8,
    room: "Living Room",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "30-90 days",
    userScheduled: "",
    type: "Replace"
  },
  { id: 9,
    room: "Kitchen",
    category: "Filters",
    name: "Air Filter",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "30-90 days",
    userScheduled: "",
    type: "Replace"
  },
  { id: 10,
    room: "Kitchen",
    category: "Fire Extinguisher",
    name: "Fire Extinguisher",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Check Expiration"
  },
  { id: 11,
    room: "Kitchen",
    category: "Spices",
    name: "Spices",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Check Expiration"
  },
  { id: 12,
    room: "Bedroom",
    category: "Carbon Monoxide Detector",
    name: "Carbon Monoxide Detector",
    brand: "",
    model: "",
    purchaseLocation: "",
    recommendation: "yearly",
    userScheduled: "",
    type: "Check Expiration"
  },
]